// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "tracker.enable": boolean;
      "tracker.sampleSeconds": number;
      "tracker.idleSeconds": number;
      "tracker.flushSeconds": number;
      "statusAuto.enable": boolean;
      "statusAuto.readThreshold": number;
      "statusAuto.minMinutes": number;
      "column.reading.enable": boolean;
      "column.status.enable": boolean;
      "column.rating.enable": boolean;
      "column.tags.enable": boolean;
      "column.textTags.enable": boolean;
      "column.annots.enable": boolean;
      "annots.style": string;
      "annots.color": string;
      "heat.color": string;
      "heat.opacity": string;
      "titleDecor.heat": boolean;
      "titleDecor.unreadBold": boolean;
      "titleDecor.unreadIncludesEmpty": boolean;
      "tags.hideInTitle": boolean;
      "textTags.match": string;
      "textTags.color": string;
      "textTags.textColor": string;
      "rating.mark": string;
      "rating.option": string;
      "rating.color": string;
      "rating.extraKey": string;
      "network.email": string;
      "network.cacheTTLHours": number;
      "statusAuto.markEmpty": boolean;
      "extra.stripOnExport": boolean;
      "reader.schemes": boolean;
      "graph.visible": boolean;
      "graph.mode": string;
      "graph.height": number;
      "graph.maxNodes": number;
      "nestedTags.show": boolean;
      "nestedTags.linkSymbol": string;
      "nestedTags.sort": string;
      "nestedTags.showAllTags": boolean;
      "nestedTags.matchChildTags": boolean;
      "column.pubtags.enable": boolean;
      "column.if.enable": boolean;
      "column.venue.enable": boolean;
      "rank.fields": string;
      "rank.sortBy": string;
      "rank.map": string;
      "rank.colors": string;
      "rank.defaultColor": string;
      "rank.textColor": string;
      "rank.opacity": string;
      "rank.ttlDays": number;
      "rank.useEasyScholar": boolean;
      "rank.useOpenAlex": boolean;
      "rank.autoFetch": boolean;
      "secret.easyscholar": string;
      "if.field": string;
      "if.max": number;
      "if.progress": boolean;
      "if.info": boolean;
      "if.color": string;
      "collectionCounts.enable": boolean;
      "collectionCounts.mode": number;
    };
  }
}
