// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "tracker.enable": boolean;
      "tracker.sampleSeconds": number;
      "tracker.idleSeconds": number;
      "tracker.flushSeconds": number;
      "statusAuto.enable": boolean;
      "statusAuto.readThreshold": number;
      "statusAuto.minMinutes": number;
      "column.reading.enable": boolean;
      "column.status.enable": boolean;
      "column.rating.enable": boolean;
      "column.tags.enable": boolean;
      "column.textTags.enable": boolean;
      "heat.color": string;
      "heat.opacity": string;
      "titleDecor.heat": boolean;
      "titleDecor.unreadBold": boolean;
      "tags.hideInTitle": boolean;
      "textTags.match": string;
      "textTags.color": string;
      "network.email": string;
      "network.cacheTTLHours": number;
    };
  }
}
